name: Java CI with Gradle

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Получаем код из репозитория
      - uses: actions/checkout@v3

      # 2. Настраиваем JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # 3. Даем права на выполнение gradlew
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 4. Запускаем SUT в фоне
      - name: Start SUT
        run: java -jar ./artifacts/app-ibank-build-for-testers.jar &

      # 5. Запускаем тесты через Gradle в headless режиме
      - name: Run tests
        run: ./gradlew test --info -Dselenide.headless=true
